### PR TITLE
Start putting the fiber docs together

### PR DESCRIPTION
**Pull request by iamdustan**

### CODE REVIEW

**Comment by oatkiller** [comment]
👍 Not sure if this is ready, but I am eager to learn!

**Comment by ManasJayanth** [comment]
@iamdustan First off, great work. Love this repo. Based on [TinyRenderer](https://github.com/iamdustan/tiny-react-renderer/blob/fiber/src/fiber/ReactTinyFiber.js) I did manage to write a bare basic dom and canvas renderer. (I can share it if you like).

Do you have any kind of notes/links/react PRs/github comments that can be referred. 1. I'd like to contribute here. 2. I want to make sure I'm on the right path writing renderers for fiber.

**Comment by iamdustan** [comment]
Oh I suppose I could land this 😅 

@prometheansacrifice I don’t have any PRs for reference off-hand, but I do want to add those references to this repo/documentation as relevant.

**Comment by ManasJayanth** [comment]
Here's what I dug up

1. First fiber commit using a Noop Renderer: [New Reconciler Infra](https://github.com/facebook/react/pull/6690/files)
2. First commit integrating Host environment API: [Host environment side-effects](https://github.com/facebook/react/commit/62d4561910aa6c8f07ddd0f40415b70e546b81dc)
3. Paul Irish's [links](https://github.com/acdlite/react-fiber-architecture/issues/5)
4. List of [Fiber PRs](https://github.com/facebook/react/pulls?utf8=%E2%9C%93&q=is%3Apr%20%5Bfiber%5D)

**Comment by ManasJayanth** [comment]
Appendix files are empty. Most likely, what is going to be the content of [Rendering-A-Top-Level-Element](https://github.com/iamdustan/tiny-react-renderer/blob/fiber/appendix/1-Rendering-A-Top-Level-Element.md) and [Reconcile-Transaction](https://github.com/iamdustan/tiny-react-renderer/blob/fiber/appendix/2-Reconcile-Transaction.md)?

**Comment by kevzettler** [comment]
Is this good to merge? I'm attempting to write a renderer and found this repo. Seems the /stack examples are not up to date and fiber is about to land in react. Should I use this branch as a resource?

**Comment by kevzettler** [comment]
@prometheansacrifice I would appreciate a look at your canvas renderer if you don't mind

**Comment by ManasJayanth** [comment]
@kevzettler Just to illustrate, I've put together a [snippet](https://gist.github.com/prometheansacrifice/6e2c75ea5df988c4ae6ea778710287ba). Try it with a simple component like 

```
const HelloWorld = ({ name }) => <div>Hello there <span>{ name }</span></div>;
```

It will however fail for stateful components.

```
class HelloWorld extends Component {
  constructor() {
    super();
    this.state = {
      counter: 0
    };
  }
  componentDidMount() {
    setInterval(() => {
      this.setState((state, props) => {
        return {
          counter: state.counter + 1
        };
      });
    }, 1000);
  }
  render() {
    return (
      <div>
      counter is <span>{ this.state.counter }</span>
      </div>
    );
  }
}
```
Canvas is a immediate mode api and doesn't work well as is. You might want to look at [ART](https://github.com/sebmarkbage/art) and use it to write a renderer yourself (Though react officially has `react-art`) I did get a chance to write this myself, but let me know if I can help.

Which brings me to another question: Is react suited only for retained mode graphics? (Will probably open a SO question)

**Comment by iamdustan** [comment]
A bit premature perhaps, but I’ll still land this for now. It won’t work with the latest React 16 releases due to flat bundles, but if you stumble across this you can follow https://github.com/facebook/react/issues/9103 for whenever a solution does land.

**Pull request merged**
